[package]
name = "rust_rp2a03"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.8.0"
bitflags = "2.1.0"
env_logger = "0.10.0"
lazy_static = "1.4.0"
log = "0.4.18"
rand = "0.8.5"
sdl2 = "0.35.2"
